### ISSUE TITLE
Error 500 when authenticating via StackExchange

### ISSUE THREAD

**Issue by rubek** [softwerkskammer/Agora#1035]
See attached screenshot. I sometimes am logged in after reloading, sometimes not.

![screen shot 2016-02-17 at 09 27 12](https://cloud.githubusercontent.com/assets/11096153/13103796/4d431fd0-d559-11e5-955c-ed0eff54ab57.png)

**Comment by leider** [comment]
Ich kann das nicht reproduzierbar hinkriegen. Ab und an erhalte ich den Fehler lokal auch. Vermutlich immer beim ersten mal.

Für sachdienliche Hinweise bin ich dankbar

**Comment by NicoleRauch** [comment]
@georgberky I will track your issue here. Will have a look at it soon.

**Comment by georgberky** [comment]
Thanks for working on it.

**Comment by dnno** [comment]
I can't use the stackoverflow login option at all, since a few days. Any new on this?

**Comment by chr1shaefn3r** [comment]
Same here, can't login with stackoverflow/stackexchange login option anymore.
Getting a different error though:
![2016-08-13_softwerkskammer org_500_authentication-error](https://cloud.githubusercontent.com/assets/11996484/17645924/f8874eca-61b3-11e6-9c01-23bf1f8ad909.png)

**Comment by NicoleRauch** [comment]
OK folks, sorry for the long delay. I've started looking into it. I don't have a solution yet, but I will document here what I learned so far. Maybe somebody knows something or can help in any way...

When logging into softwerkskammer.org, these login errors occur each time. When logging in locally, the error only occurs on the first login. On subsequent attempts, the login works fine. After deleting the cookie "openid.stackexchange.com", the error usually occurs again.

I'm getting the error message "Invalid association handle" on my machine. It occurs because the association could not be loaded. This happens in node_modules/passport-openid/node_modules/openid/openid.js:1105.

What is this association about? (also see http://openid.net/specs/openid-authentication-2_0.html#associations) 
When starting the openid authentication, the provider passes this association to us, and we save it in a list of associations.
After the user provided her credentials, the provider calls the callback url we pass to it, and it appends a long list of parameters, one of them being "openid.assoc_handle". The openid module then looks up the association in its list of already saved associations (the assoc_handle being the key for the lookup). Interestingly, the association passed initially gets stored with a different key than the one which is passed in the assoc_handle. That's why this error is being triggered.

**Comment by sengaya** [comment]
FTR, I'm getting this error on https://www.socrates-conference.de every time now (login via launchpad.net OpenID). If I remember this correctly, it worked without any issues until 2-3 weeks ago.

**Comment by leider** [comment]
new insights from debugging leading to error: "invalid signature":

params = {
  "openid.claimed_id": "https://openid.stackexchange.com/user/dff03c7f-21ef-46a4-83ed-8ccede2aa294",
  "openid.identity": "https://openid.stackexchange.com/user/dff03c7f-21ef-46a4-83ed-8ccede2aa294",
  "openid.sig": "LzWvYiaNcb2h9lDDNzka812cegQyLy4vB6v9/m9ChLE=",
  "openid.signed": "claimed_id,identity,assoc_handle,op_endpoint,return_to,response_nonce,ns.sreg,sreg.email,ns.alias3,alias3.mode,alias3.type.alias1,alias3.value.alias1",
  "openid.assoc_handle": "Dhvq!IAAAAIPASt6vOdeXeLJ7tQTukNi-5hcFzKJAUr5cTvh07WgwQQAAAAFn6KubE5XE6gf6_LzLD7MKDPaGWIf47ZrG98NeCtughga-0tdJgxNKP1NGVIqXYXQXZmnpgGqwZWv2RCupV9EX",
  "openid.op_endpoint": "https://openid.stackexchange.com/openid/provider",
  "openid.return_to": "http://localhost:17124/auth/openid/callback",
  "openid.response_nonce": "2016-08-28T15:43:11ZoRox0bjK",
  "openid.mode": "id_res",
  "openid.ns": "http://specs.openid.net/auth/2.0",
  "openid.ns.sreg": "http://openid.net/extensions/sreg/1.1",
  "openid.sreg.email": "derleider@web.de",
  "openid.ns.alias3": "http://openid.net/srv/ax/1.0",
  "openid.alias3.mode": "fetch_response",
  "openid.alias3.type.alias1": "http://axschema.org/contact/email",
  "openid.alias3.value.alias1": "derleider@web.de"
}

association = {
  "provider": {
    "endpoint": "https://openid.stackexchange.com/openid/provider",
    "version": "http://specs.openid.net/auth/2.0"
  },
  "type": "sha256",
  "secret": "NRXZEepEL7K/pHsFiKG7LC4vYKEqdYwawInkRw9wGlo="
}

in openid.js (v2.0.2) Line 1224 (var _checkSignatureUsingAssociation = function(params, callback))

to be isolated further in tests

**Comment by chr1shaefn3r** [comment]
I studied the OpenId2-Spec for [generating signatures](https://openid.net/specs/openid-authentication-2_0.html#generating_signatures), but couldn't find an issue.
To me it looks like openid.js is doing the right thing ...

**Comment by NicoleRauch** [comment]
@leider This is only the subsequent error, isn't it? The root cause problem is that the server initially passes an association with a handle to us and then, when the user wants to authenticate, that request comes back with a different association handle. The question is, why are there two different handles being returned from the server?

**Comment by leider** [comment]
Yes. The subsequent but show-stopping problem. 
We should focus on that and afterwards return to the association

**Comment by NicoleRauch** [comment]
But isn't it triggered *because* the association comes back with a different handle than the authorization request? How do you plan to address the subsequent problem without addressing the root cause?

**Comment by NicoleRauch** [comment]
Ah, I see - you are talking about the other error. Can you reproduce that? I couldn't.

**Comment by leider** [comment]
Problem found and PR issued with node-openid. Root cause is - what else did we expect - a breaking change in the nodejs crypto library: they changed the applied encoding from 'binary' to 'utf-8' thus the key provided for Hmac digesting is interpreted the wrong way leading to incorrect results.

Really looking forward to co-working with professionals. And I do not mean my dear softwerkers!

**Comment by dnno** [comment]
Great, thank you very much for investigating and fixing this issue. Looking forward to log in again! Out of curiosity, did this really only affect the stackoverflow login option then?

**Comment by georgberky** [comment]
Great job, thank you so much! Must have been quite some work to find the root cause. 👍

**Comment by NicoleRauch** [comment]
Wow, great job!

**Comment by leider** [comment]
It's not fixed. I'm still experiencing the symptoms in the integrated system. :(

Will do a pairing session on Sunday. Never fight alone!!

**Comment by leider** [comment]
one more changed line and currently (localhost) both problems seem to have disappeared. 🎱 

now waiting for new version (even compatible with passport's requirements)

bottom line: watch out where the huskies go - don't you eat that yellow snow

**Comment by leider** [comment]
integrated and verified
