### ISSUE TITLE
Rework the registration grid so that it always sends people to the waitinglist

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1152]
- multiple selections must be possible
- only one selection per row
- remove the waitinglist checkboxes
- always emit waitinglist events instead of registration events
- change the waitinglist events so that they take the given duration

**Comment by NicoleRauch** [comment]
First step: The backend accepts the waitinglist duration as it gets submitted from the frontend. When accepting somebody from the waitinglist, the given duration is used subsequently. There should not be any other changes to the backend and events etc.

Second step: The radiobutton grid on the registration page already sends waitinglist information (including the duration). The waitinglist checkboxes are removed. Each line consists of mutually exclusive radio buttons, but the user can select multiple lines. (Make this visually discoverable.)

**Comment by leider** [comment]
Your proposed sequence is not really possible without changing the datastructure in the events. I'd like to go for this:
1. change the UI so that the radio buttons now work as waitinglist wishes. The UI would so send a max of 4 waitinglist registrations (with potentially different durations) to the backend. We need tha table on the UI for showing the prices. (I already spiked that and it looks great)
2. extend the already existing waitinglist events with an array (ugly, I know) of durations matched by index with the waitinglist array
3. Later we need to change subsequent functions in the backend like the display of the waitinglists, enabling a user to change (add, remove) his already submitted waitinglist wishes although she is already booked in a room.

P.S.: I'd really enjoy a clarification in wording (code) to distinguish between reservation, registration, waitinglist and so on :)
