### ISSUE TITLE
UI for creating a blog entry

### ISSUE THREAD

**Issue by UrsMetz** [softwerkskammer/Agora#1302]
As discussed with @NicoleRauch I want to add a (simple) UI to make it easier to create a blog entry: Today one has to know the "magic" prefix format ("blog_dateAsYYYY-MM-DD") for a wiki site so that Agora recognizes it as a blog entry.

My proposal is the have a "button" (actually a link styled like a button) or "normal" link on the group page that links to a form with two inputs: one for the date and one for the name part of the wiki page name.
When a user inserts "2017-11-19" as the date and "my cool title" this would result in the wiki page name "blog_2017-11-19_my-cool-title".

Now here are my questions:
1. Would you prefer a "normal" link or a link looking like a button? I think a link styled like a button gets more attention and is the UI element I would expect.
1. Should there be a new `express` top level route "/blog/:groupName" where the form page is reachable? Technically it is a form for creating a new wiki page (and thus could go under e.g. "/wiki/:groupName/newBlogEntry") but "/blog" might be closer to the domain?
1. Is there already code for sanitizing a string to be a valid URL path segment? In the example above the whitespaces would be replaced by `-` (I think it is not strictly necessary) other characters like "/" definitely have to be replaced. I found `renderer#normalize`. Would that be a suitable function for that purpose?

**Comment by NicoleRauch** [comment]
Hi Urs,

excellent :-)

This is not a complete reply but hopefully something that can get you started. Maybe @leider can chime in too ;-)

1. I think most actions are styled as buttons, so that would be the way to go. I'm wondering whether it should go into the button bar at the top of the group page or whether it should be somewhere else on the page? (My reflexes say it would be nice in the bar, but only if we can find a nice icon for it.)

2. Right now the top-level routes usually indicate modules (you can see that if you compare the routes list in the app with the directory list). So I am not sure whether we want this to be a module on its own? (My reflexes say no, but maybe I underestimate its size and stand-alone-ness.)

3. There must be something in the wiki module; if you look at the tests you will easily find it ;-)

4. I would like the user to pick the date from a date picker, or even nicer, let the user create a blog post for an activity, so there is no need to enter any date at all (because the activity already knows it). Yes, I think that's where I'd put it. Just a button "Create blog post" on an activity. Use the date and group information and create a new page for the user to edit. What do you think?

**Comment by UrsMetz** [comment]
Ad 4.: so the user doesn't have to insert anything? That would make is really easy :-):
Just construct the link from the date of the activity and the address suffix. So no form and thus no form validating needed. So I would go with this easy solution. This also answers 2.

Late we might add the more flexible solution with the form to freely choose the blog entry name.

**Comment by NicoleRauch** [comment]
Yes, something like this. I think the address suffix has nothing to do with these, but activity name and group might contain interesting information ;-)

Yep, and I totally agree with the "later" plan ;-)

**Comment by leider** [comment]
Maybe the simplest way is a button on the activity‘s page just opening the associated wiki page. ???

**Comment by UrsMetz** [comment]
I submitted the pull request #1305 where I exactly took the route you proposed: just a link to the associated wiki page :-).
